# Generated by Django 3.2.1 on 2021-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='admin',
            new_name='visibility',
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(max_length=5000),
        ),
    ]
